//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class userinfo
    {
        public int id { get; set; }
        [Display(Name ="UserName")]
        [Required(ErrorMessage ="Please enter the username")]

        public string username { get; set; }

        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Please enter the password")]
        public string password { get; set; }


        [Display(Name = "confirm-Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Please re-enter the same password")]
        public string Re_password { get; set; }

    }
}
